apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-svvr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-svvr@sha256:e7bd3a92041d40c48afd2f7496cd3d2aded6e482054e7b9f619d22f208971f81
        name: my-nodejs
        resources: {}
status: {}
